# Generated by Django 6.0.5 on 2026-06-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
    ]
