# Generated by Django 6.0.5 on 2026-06-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harithamission', '0003_remove_wastepickup_staff_delete_staff'),
        ('staffapp', '0002_remove_staff_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='created_at',
            new_name='joined_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='assigned_pickups',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('collection', 'Collection Staff'), ('driver', 'Driver'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], default='collection', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='StaffDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField()),
                ('duty_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_duties', to='harithamission.mission')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='staffapp.staff')),
            ],
        ),
    ]
