# Generated by Django 6.0.5 on 2026-06-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harithamission', '0003_remove_wastepickup_staff_delete_staff'),
        ('staffapp', '0003_rename_created_at_staff_joined_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField()),
                ('duty_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_duties', to='harithamission.mission')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_duties', to='staffapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='WastePickupDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField()),
                ('duty_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_duties', to='staffapp.staff')),
                ('waste_pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_duties', to='harithamission.wastepickup')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffDuty',
        ),
    ]
