# Generated by Django 6.0.5 on 2026-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0005_staff_password_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionduty',
            name='duty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionduty',
            name='duty_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastepickupduty',
            name='duty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastepickupduty',
            name='duty_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
