# Generated by Django 6.0.5 on 2026-06-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harithamission', '0002_staff_wastepickup_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastepickup',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
